app:
  title: "Mashhad Airport Assistant"
  page_icon: "ğŸ“š"
  layout: "centered"
  header: "Mashhad Airport Assistant"
  welcome_message: "Ø³Ù„Ø§Ù… ğŸ‘‹ØŒ Ù…Ù† Ù…ÛŒ ØªÙˆÙ†Ù… Ø¨Ù‡ Ø³ÙˆØ§Ù„Ø§Øª Ø´Ù…Ø§ Ø¯Ø±Ø®ØµÙˆØµ ÙØ±ÙˆÚ¯Ø§Ù‡ Ù…Ø´Ù‡Ø¯ Ùˆ Ù‡Ù…ÛŒÙ†Ø·ÙˆØ± Ù…Ù†Ø´ÙˆØ± Ø­Ù‚ÙˆÙ‚ Ù…Ø³Ø§ÙØ± Ù¾Ø§Ø³Ø® Ø¨Ø¯Ù…. Ú†Ù‡ Ø³ÙˆØ§Ù„ÛŒ Ø¯Ø§Ø±ÛŒØ¯ØŸ "

data:
  pdf_paths:
    - "data/CV.pdf"
    - "data/Cover_Letter.pdf"

llm:
  model_name: "models/gemini-2.5-flash"
  temperature: 0.2

embedding:
  model_name: "aligh4699/heydariAI-persian-embeddings"
  
rag:
  chunk_size: 1000
  chunk_overlap: 100
  top_k: 4

chat:
  history_limit: 6
